spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jwt_security
        username: postgres
        password: Bebong123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
            database: jwt_security
            database-platform: org.hibernate.dialect.PostgreSQLDialect


